[versions]
agp = "8.9.1"
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
